name: Android CI (testing)

on:
  push:
    branches: ["testing/v1.0.0"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_MODULE: app
      LOG_DIR: out/LOGS
      APK_DIR: out/APK
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Android SDK 33 & build-tools 33.0.2
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build debug
        run: |
          set -euxo pipefail
          mkdir -p "${LOG_DIR}" "${APK_DIR}"
          gradle --no-daemon --stacktrace :${APP_MODULE}:assembleDebug 2>&1 | tee "${LOG_DIR}/gradle.log"
          shopt -s globstar nullglob
          cp -a ${APP_MODULE}/build/outputs/**/*.apk "${APK_DIR}/" || true
          cp -a ${APP_MODULE}/build/outputs/**/*.aab "${APK_DIR}/" || true
          ls -R out || true

      - name: Upload LOGS
        uses: actions/upload-artifact@v4
        with:
          name: LOGS
          path: out/LOGS/**
          if-no-files-found: warn

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: out/APK/**
          if-no-files-found: warn
