name: Android CI (testing)

on:
  push:
    branches: ["testing/v1.0.0"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_MODULE: app
      LOG_DIR: out/LOGS
      APK_DIR: out/APK
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Uses the repo's Gradle Wrapper (now pinned to 8.7)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK (API 33, build-tools 33.0.2)
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2
          components: |-
            platforms;android-33
            build-tools;33.0.2
            platform-tools

      - name: Build debug
        run: |
          set -euxo pipefail
          mkdir -p "${LOG_DIR}" "${APK_DIR}"
          ./gradlew --no-daemon --stacktrace :${APP_MODULE}:assembleDebug 2>&1 | tee "${LOG_DIR}/gradle.log" || true
          shopt -s globstar nullglob
          cp -a ${APP_MODULE}/build/outputs/**/*.apk "${APK_DIR}/" || true
          cp -a ${APP_MODULE}/build/outputs/**/*.aab "${APK_DIR}/" || true
          ls -R out || true
        # don't fail this step early; we still want artifacts in the next steps
        continue-on-error: true

      - name: Upload LOGS
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: LOGS
          path: out/LOGS/**
          if-no-files-found: warn

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: out/APK/**
          if-no-files-found: warn

      # Re-fail the job if the build actually failed
      - name: Fail if build failed
        if: steps.build.outcome == 'failure'
        run: |
          echo "::error ::Gradle build failed — see LOGS artifact for details."
          exit 1
