name: Android CI (Debug APK)

on:
  push:
    branches: [ "main", "mvp", "feature/**" ]
  pull_request:
    branches: [ "main", "mvp", "feature/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0"
          yes | sdkmanager --licenses

      - name: Setup Gradle 7.6 (no wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "7.6"

      - name: Build Debug APK
        run: gradle :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Grimoire-of-Growth-debug
          path: app/build/outputs/apk/debug/app-debug.apk
