name: Android CI (release only)

on:
  push:
    branches: ["release/v1.0"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android commandline tools
        run: |
          set -eux
          SDK_ROOT=/usr/local/lib/android/sdk
          sudo mkdir -p "$SDK_ROOT"
          cd "$SDK_ROOT"
          curl -fsSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          sudo unzip -q cmdtools.zip -d cmdline-tools
          sudo mv cmdline-tools/cmdline-tools cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$SDK_ROOT" >> $GITHUB_ENV
          echo "$SDK_ROOT/cmdline-tools/latest/bin:$SDK_ROOT/platform-tools" >> $GITHUB_PATH
          yes | $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install platforms & build-tools
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Gradle 7.6
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6

      - name: Build debug & capture log
        run: |
          mkdir -p out/LOGS out/APK
          set -o pipefail
          gradle --no-daemon --stacktrace :app:assembleDebug 2>&1 | tee out/LOGS/gradle.log
          shopt -s globstar nullglob
          cp -a app/build/outputs/**/*.apk out/APK/ || true
          cp -a app/build/outputs/**/*.aab out/APK/ || true
          ls -R out || true

      - name: Upload LOGS artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.ref_name }}-${{ github.run_number }}
          path: out/LOGS/**
          if-no-files-found: warn
          retention-days: 30

      - name: Upload APKs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apks-${{ github.ref_name }}-${{ github.run_number }}
          path: out/APK/**
          if-no-files-found: warn
          retention-days: 30
