name: Android CI (Debug APK, always logs)

on:
  push:
    branches: [ "main", "mvp", "feature/**" ]
  pull_request:
    branches: [ "main", "mvp", "feature/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare log dir
        run: |
          mkdir -p ci-logs
          echo "run started: $(date -u)" | tee ci-logs/run.txt

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        shell: bash
        run: |
          set -o pipefail
          {
            sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0"
            yes | sdkmanager --licenses
          } |& tee -a ci-logs/01_android-sdk.log

      - name: Install Gradle 7.6 (SDKMAN)
        shell: bash
        run: |
          set -o pipefail
          {
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 7.6
            gradle -v
          } |& tee -a ci-logs/02_gradle-install.log

      - name: Generate Gradle Wrapper 7.6 (if missing)
        shell: bash
        run: |
          set -o pipefail
          {
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            if [ ! -f "./gradlew" ]; then
              gradle wrapper --gradle-version 7.6 --distribution-type bin
              chmod +x gradlew
            fi
            ./gradlew -v
          } |& tee -a ci-logs/03_wrapper-gen.log

      - name: Sanity check for bad 'module(' usage
        shell: bash
        run: |
          if grep -R "module(" -n .; then
            echo "::error::Found 'module(' in Gradle files. Use \"module: 'name'\" in excludes."
            exit 1
          fi

      - name: Build Debug APK (capture log)
        shell: bash
        run: |
          set -o pipefail
          ./gradlew :app:assembleDebug --stacktrace |& tee -a ci-logs/04_build.log
          echo $? > ci-logs/build.exit

      - name: Upload Debug APK (if build succeeded)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Grimoire-of-Growth-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: warn

      - name: Upload logs (ALWAYS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            ci-logs/**
            **/build/reports/**
            **/build/*.log
            **/outputs/logs/**
          if-no-files-found: warn
