name: Android CI (testing)

on:
  push:
    branches: [ "testing/v1.0.0" ]
  workflow_dispatch:

jobs:
  build:
    if: github.ref_name == 'testing/v1.0.0'
    runs-on: ubuntu-latest
    env:
      APP_MODULE: app
      LOG_DIR: out/LOGS
      APK_DIR: out/APK

    steps:
      - name: Checkout testing branch
        uses: actions/checkout@v4
        with:
          ref: testing/v1.0.0

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android commandline tools
        run: |
          set -eux
          SDK_ROOT=/usr/local/lib/android/sdk
          sudo mkdir -p "$SDK_ROOT"
          cd "$SDK_ROOT"
          curl -fsSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          sudo unzip -q cmdtools.zip -d cmdline-tools
          sudo mv cmdline-tools/cmdline-tools cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$SDK_ROOT" >> $GITHUB_ENV
          echo "$SDK_ROOT/cmdline-tools/latest/bin:$SDK_ROOT/platform-tools" >> $GITHUB_PATH
          yes | $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install platforms & build-tools
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Use Gradle 7.6 (no cache)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.6
          cache-disabled: true

      - name: Build debug & capture log
        run: |
          set -euxo pipefail
          mkdir -p "${LOG_DIR}" "${APK_DIR}"
          gradle --no-daemon --stacktrace :${APP_MODULE}:assembleDebug 2>&1 | tee "${LOG_DIR}/gradle.log"
          shopt -s globstar nullglob
          cp -a ${APP_MODULE}/build/outputs/**/*.apk "${APK_DIR}/" || true
          cp -a ${APP_MODULE}/build/outputs/**/*.aab "${APK_DIR}/" || true
          ls -R out || true

      - name: Upload LOGS (testing)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-testing-v${{ github.run_number }}
          path: ${{ env.LOG_DIR }}/**
          if-no-files-found: warn
          retention-days: 30

      - name: Upload APKs (testing)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apks-testing-v${{ github.run_number }}
          path: ${{ env.APK_DIR }}/**
          if-no-files-found: warn
          retention-days: 30
