name: Android CI (Debug APK, always logs)

permissions:
  contents: write

on:
  push:
    branches: [ "main", "mvp", "feature/**" ]
  pull_request:
    branches: [ "main", "mvp", "feature/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare log dir
        run: |
          mkdir -p ci-logs
          echo "run started: $(date -u)" | tee ci-logs/00_run.txt

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Base SDK only; we'll install packages manually to capture logs
      - name: Setup Android SDK (base)
        uses: android-actions/setup-android@v3

      - name: Install Android packages (logged + retry)
        shell: bash
        run: |
          set -o pipefail
          tries=0
          until [ $tries -ge 3 ]; do
            {
              sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;31.0.0"
            } |& tee -a ci-logs/01_android-sdk.log
            code=${PIPESTATUS[0]}
            echo "$code" > ci-logs/01_android-sdk.exit
            [ $code -eq 0 ] && break
            tries=$((tries+1))
            echo "retry $tries/3 in 5s…" | tee -a ci-logs/01_android-sdk.log
            sleep 5
          done
          yes | sdkmanager --licenses |& tee -a ci-logs/01_android-sdk.log || true

      - name: Setup Gradle 7.6
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "7.6"

      - name: Build Debug APK (capture log)
        shell: bash
        continue-on-error: true
        run: |
          set -o pipefail
          gradle -v |& tee -a ci-logs/02_gradle-version.log
          gradle :app:assembleDebug --stacktrace |& tee -a ci-logs/04_build.log
          echo "${PIPESTATUS[0]}" > ci-logs/04_build.exit

      - name: Upload Debug APK (if present)
        if: ${{ hashFiles('app/build/outputs/apk/debug/app-debug.apk') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: Grimoire-of-Growth-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: warn

      - name: Upload logs (ALWAYS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ci-logs/**
          if-no-files-found: warn
          retention-days: 7

      - name: Push logs to ci-logs branch (ALWAYS)
        if: always()
        shell: bash
        continue-on-error: true
        run: |
          RUN_DIR="runs/${{ github.run_id }}"
          git config user.name "CI Logs Bot"
          git config user.email "actions@users.noreply.github.com"
          git fetch origin ci-logs || true
          git checkout -B ci-logs origin/ci-logs || git checkout -B ci-logs
          mkdir -p "$RUN_DIR"
          cp -r ci-logs/* "$RUN_DIR"/
          git add -A
          git commit -m "logs: run ${{ github.run_id }} on ${{ github.ref_name }} @ ${{ github.sha }}" || true
          git push origin ci-logs || true

      - name: Fail if something failed
        if: always()
        shell: bash
        run: |
          fail=0
          [ -f ci-logs/01_android-sdk.exit ] && [ "$(cat ci-logs/01_android-sdk.exit)" != "0" ] && { echo "::error::SDK install failed (see 01_android-sdk.log)"; fail=1; }
          [ -f ci-logs/04_build.exit ] && [ "$(cat ci-logs/04_build.exit)" != "0" ] && { echo "::error::Build failed (see 04_build.log)"; fail=1; }
          exit $fail
